spring.application.name=Storelab
server.servlet.context-path=/api/v1

spring.datasource.url=${STORELAB_DB_URL}
spring.datasource.username=${AIVEN_DB_USER}
spring.datasource.password=${AIVEN_DB_PASS}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.security.oauth2.client.registration.google.client-id=${STORELAB_OAUTH_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${STORELAB_OAUTH_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,profile,email

api.security.token.secret=${JWT_SECRET:12345678}